context:
  version: "1.5.0"

package:
  name: ktlint
  version: ${{ version }}

source:
  url: https://github.com/pinterest/ktlint/archive/${{ version }}.tar.gz
  sha256: 3a65cfa2a97e43d3ee98c4c2b4d07244ef3a5f70ae484bb99d6339783fed84a4

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk
    - sed
  run:
    - openjdk

tests:
  - script:
      - ktlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: An anti-bikeshedding Kotlin linter with built-in formatter
  homepage: https://github.com/pinterest/ktlint
  repository: https://github.com/pinterest/ktlint

extra:
  recipe-maintainers:
    - danielnachun
