context:
  version: 1.4.1

package:
  name: ktlint
  version: ${{ version }}

source:
  url: https://github.com/pinterest/ktlint/archive/${{ version }}.tar.gz
  sha256: cd36491e70afe25789c16752a2358e504141eea877234bca4a4e14531c5ddb71

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk
    - sed
  run:
    - openjdk

tests:
  - script:
      - ktlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: An anti-bikeshedding Kotlin linter with built-in formatter
  homepage: https://github.com/pinterest/ktlint
  repository: https://github.com/pinterest/ktlint

extra:
  recipe-maintainers:
    - danielnachun
